apiVersion: v1
kind: ConfigMap
metadata:
  name: config
data:
  token: "1820850136:AAH1WrMh6xvLo2bCKIAUV4az16YrTf0wp_w"
  url: http://util.ao5.in/
  stand: prod
  database: postgresql://postgres:postgres@10.0.19.31:31642/utility
  admins: "479844252"
