apiVersion: apps/v1
kind: Deployment
metadata:
  name: util-bot
  namespace: dev-utils
  labels:
    name: util-bot
spec:
  replicas: 1
  selector:
    matchLabels:
      name: util-bot
  template:
    metadata:
      labels:
        name: util-bot
    spec:
      securityContext:
        runAsUser: 0
        fsGroup: 0
      containers:
        - name: util-bot
          image: utilbot:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: BOT_TOKEN
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: token
            - name: UTIL_URL
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: url
            - name: STAND
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: stand
            - name: DATABASE
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: database
            - name: ADMINS
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: admins
      restartPolicy: Always
